apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ip-whitelister.fullname" . }}
  labels:
    {{- include "ip-whitelister.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ .Values.config | nindent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ip-whitelister.fullname" . }}-resources
  labels:
    {{- include "ip-whitelister.labels" . | nindent 4 }}
data:
{{- if .Values.resource_configs }}
  {{- range $id, $resource := .Values.resource_configs }}
  {{ $resource.name }}: |-
{{ $resource.config | indent 4 }}
  {{- end }}
{{- end }}
