# Path to this config can be set via env variable 'CONFIG_FILE'
# App registration must have access to the Azure resources + Admin Consent for AzureAD
# Client Secret can also be set via env variable 'CLIENT_SECRET'
# Redis Access Token can also be set via env variable 'REDIS_TOKEN'

url: http://localhost:8080

# User whitelistings will expire/be removed after 24 hours
ttl: 24 # hours

auth:
  type: azure
  tenant_id: notreal-not-real-not-notreal
  client_id: notreal-not-real-not-notreal
  client_secret: notrealnotrealnotreal

redis:
  host: redis
  port: 6379
  token: my-sup3r-comp1ic4t3d-s3cr3t-t0k3n

defaults:
  subscription_id: notreal-default-subscription
  resource_group: notreal-default-rg

resources:
  - cloud: azure
    type: frontdoor
    subscription_id: notreal-not-real-not-notreal
    resource_group: notreal-rg
    policy_name: notrealpolicy
  - cloud: azure
    type: storageaccount
    subscription_id: notreal-not-real-not-notreal
    resource_group: notreal-rg
    name: notrealstorage
    group:
      - b111111a-b11a-111a-bb11-1a111aaa11a11 # group object id
  - cloud: azure
    type: keyvault
    subscription_id: notreal-not-real-not-notreal
    resource_group: notreal-rg
    name: notrealkeyvault
  - cloud: azure
    type: postgres
    subscription_id: notreal-not-real-not-notreal
    resource_group: notreal-rg
    name: notpostgresserver
    ip_whitelist:
      - 51.0.0.0/24 # my company proxy addresses 3
    group:
      - a111111a-a11a-111a-aa11-1a111aaa11a11 # group object id
  - cloud: azure
    type: redis
    subscription_id: notreal-not-real-not-notreal
    resource_group: notreal-rg
    name: notrealredis
  - cloud: azure
    type: cosmosdb
    subscription_id: notreal-not-real-not-notreal
    resource_group: notreal-rg
    name: notrealcosmosdb
    ip_whitelist: # https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-configure-firewall#allow-requests-from-the-azure-portal
      - 104.42.195.92
      - 40.76.54.131
      - 52.176.6.30
      - 52.169.50.45
      - 52.187.184.26

# This whitelist will be applied to all resources and should be static non-human IPs only
ip_whitelist:
  - 85.0.0.0/24 # my company proxy addresses 1
  - 200.0.0.0/24 # my company proxy addresses 2
