resources:
  - cloud: azure
    type: cosmosdb
    subscription_id: notreal-not-real-not-notreal
    resource_group: app1-notreal-rg
    name: app1-notrealcosmosdb
    ip_whitelist: # https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-configure-firewall#allow-requests-from-the-azure-portal
      - 104.42.195.92
      - 40.76.54.131
      - 52.176.6.30
      - 52.169.50.45
      - 52.187.184.26
