name: go test

on:
  pull_request:
  push:

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Vet
        run: go vet
      -
        name: Build
        run: go build -v
      -
        name: Test
        run: go test -v
